In [1]:
""" Chapter 09: Unserpervised Learning Techniques """

# Unsupervised learning would be the cake,
# supervised Learing would be the icing on the cake, 
# and reinforcement learning would be the cherry on the cake

# Wouldn't it be great if the algorithm could just exploit the unlabled data without needing humans to labele every picture?
# that's unsupervised learning!

# - Clustering
# - Anomaly Detection or Outlier Detection
# - Density Estimation

' Chapter 09: Unserpervised Learning Techniques '

In [2]:
""" Clustering Algorithms: K-means and DBSCAN """

# It is the task of identifying similar instances and assigning them to clusters or groups of similar instances.
# Just like in classification, each instance gets assigned to a group,
# However, unlike classification, clustering is an unsupervised task.

# There're 2 side datasets = A labeled dataset and without the labels.
# Clustering algorithms can make good use of all features, so in fact they identify the three clusters fairly well.

# Clustering is used in a wide variety of applications,

# 1. Customer Segmentation = Can be useful in recommender systems to suggest content that other users in the same cluster enjoyed.
# 2. Data Analysis = Can be helpful to run a clustering algorithm, and then analyze each cluster separately.
# 3. Dimensionality Reduction = Measure each instances's affinity with each cluster; affinity is any measure of how well an instance fits into a cluster,
# 3.1 If there are k-clusters, then this vector is k-dimensional. The new vector is typically much lower-dimensional than the original feature vector, but it can preserve enough information for further processing.
# 4. Feature engineering = k-means add geographic cluster affinity features to the California housing dataset, and they helped us get better performance.
# 5. Anomaly Detection = If I have clustered the users of my website based on their behavior, I can detect users with unsual behavior, such as an unsual number of requests per second.
# 6. Semi-Supervised Learning = If i only have a few labels, I could perform clustering and propagate the labels to all the instances in the same cluster.
# 7. Search Engines = Some search engines let me search for images that are similar to a reference image. To build such a system, I would first apply a clustering algorithm to all the images in my dataset
# 7.1 Similar images would end up in the same cluster. Use it for trained clustering model to find the images'scluster and I could then simply return all the images from the cluster.
# 8. Image Segmentation = By clustering pixels according to their color, then replacing each pixel's color with the mean color of its cluster, it is possible to considerablhy reduce the number of different color in an image.

# Some alhorithms looks for instances centered around a particular point called "Centroid"


' Clustering Algorithms: K-means and DBSCAN '

In [ ]:
""" K-Means """

# The k-means algorithm is a simple algorithm capable of clustering the kind of data that unlabeled dataset very quickly and efficiently,
# Often in just a few iteration
# K-means is sometimes referred to as the Lloyd-Forgy algorithm

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=1000, centers=5, random_state=42) # set the parameters for make_blobs

k = 5
kmeans = KMeans(n_clusters=k, random_state=42)
y_pred = kmeans.fit_predict(X)

# Note that I have to specify the number of clusters k that the algorithm must find.
# An instance's label is the index of the cluster to which the algorithm assigns this instance;
# This is not to be confused with the class labels in classification, which are used as targets 
# Remember that clustering is an unsupervised learning task

In [5]:
y_pred

array([4, 4, 0, 4, 1, 0, 3, 1, 4, 1, 1, 0, 3, 0, 3, 0, 2, 3, 2, 1, 4, 2,
       3, 0, 2, 1, 2, 3, 1, 3, 4, 3, 1, 3, 2, 0, 1, 1, 1, 2, 1, 3, 3, 0,
       3, 0, 1, 4, 2, 0, 4, 3, 0, 2, 2, 2, 2, 0, 0, 2, 4, 3, 0, 1, 0, 4,
       3, 3, 4, 4, 3, 0, 4, 0, 3, 2, 3, 4, 1, 3, 2, 4, 0, 0, 3, 4, 2, 1,
       2, 3, 4, 3, 4, 1, 1, 0, 2, 2, 0, 3, 0, 1, 4, 0, 2, 4, 2, 0, 1, 2,
       2, 4, 0, 0, 3, 2, 3, 0, 2, 2, 0, 2, 0, 0, 0, 0, 3, 0, 2, 4, 4, 3,
       4, 1, 0, 1, 4, 1, 2, 3, 0, 2, 4, 2, 4, 4, 0, 4, 4, 1, 3, 0, 4, 4,
       2, 4, 4, 2, 3, 4, 3, 1, 3, 2, 3, 1, 1, 3, 2, 4, 0, 2, 2, 0, 1, 0,
       3, 0, 4, 1, 4, 2, 4, 3, 1, 1, 4, 0, 3, 2, 3, 2, 4, 1, 4, 2, 1, 0,
       2, 4, 0, 3, 0, 0, 3, 1, 1, 2, 1, 4, 2, 3, 3, 1, 4, 0, 0, 0, 3, 1,
       0, 0, 2, 0, 2, 1, 0, 1, 4, 4, 2, 4, 2, 4, 4, 3, 2, 2, 3, 4, 1, 3,
       0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 1, 4, 1, 2, 3, 4, 4, 2, 4, 1, 4, 3,
       4, 3, 3, 3, 0, 0, 4, 4, 3, 1, 2, 1, 0, 2, 3, 1, 1, 0, 4, 1, 0, 3,
       4, 4, 4, 2, 1, 2, 3, 1, 4, 3, 1, 1, 2, 4, 3,

In [6]:
y_pred is kmeans.labels_

True

In [7]:
# Take a look at the five centroids that the algorithm found:

kmeans.cluster_centers_

array([[-6.68630691, -6.81139455],
       [ 2.03639615,  4.26762858],
       [-2.50265159,  9.03963769],
       [-8.80798056,  7.40425704],
       [ 4.66534309,  1.87476184]])

In [8]:
# Assign a new instances to the cluster whose centroid is closet:
import numpy as np
X_new = np.array([[0,2], [3,2], [-3, 3], [-3, 2.5]])
kmeans.predict(X_new)

array([1, 4, 1, 1], dtype=int32)

In [9]:
# The k-means algorithm does not behave very well when the blobs have very different diameters because all it care about
# when assigning an instance to a cluster is the distance to the centroid
# Instead of assigning each instace to a single cluster, which is called "hard-clustering",
# it can be useful to give each instance a score per cluster, which is called "soft-clustering"

# The transform() method measures the distance from each instance to every centroid:

kmeans.transform(X_new).round(2)

array([[11.06,  3.05,  7.47, 10.33,  4.67],
       [13.09,  2.46,  8.94, 12.99,  1.67],
       [10.48,  5.19,  6.06,  7.29,  7.75],
       [10.01,  5.34,  6.56,  7.6 ,  7.69]])

In [10]:
# If you have a high-dimensional dataset and you transform it this way, you end up with a "k-dimensional" datasets
# This transformation can be a very efficient nonlinear dimensionality reduction technique

In [ ]:
""" The k-means algorithm """


# If I were given all the instance labels, I could easily locate each cluster's centroid by computing the mean of the instances in that cluster
# Start by placing the centroids randomly by picking k instances at random from the dataset and using their locations as centroids.
# # Then label the instances, update the centroids, label the instances, update the centroids, and so on untill the centroids stop moving
# the mean square distance between the instance and their closet centroids can only go down at each step and since it cannot be negative
# It's guaranteed to converge.

# The computational complexity of the algorithm is generally linear with regard to the number of instances m,
# The number of clusters k,
# and the number of dimensions n.

# This is only true when the data has a clustering structure.
# If it does not
# the complexity can increase exponentially with the number of instances.
# K-means is generally one of the fastest clustering algoritms!